Repository dnthchung/HolaWear, pull requests merged in 2024-07, with the labels that each got.

#29 BE : Product + Category + Tag + ProductDepot
  backend/controllers/categoryController.js
  backend/controllers/index.js
  backend/controllers/productController.js
  backend/controllers/productDepotController.js
  backend/controllers/tagController.js
  backend/models/index.js
  backend/models/productDepot.model.js
  backend/routes/categoryRoute.js
  backend/routes/index.js
  backend/routes/productDepotRoute.js
  backend/routes/productRoute.js
  backend/routes/tagRoute.js
  backend/server.js
Labels: documentation

#30 bugs: wrong db name + port
  backend/controllers/productController.js
  backend/controllers/userController.js
  backend/models/index.js
  backend/routes/userRoute.js
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/SideBarAdmin.jsx
  frontend/src/components/Spinner.jsx
  frontend/src/components/admin/ProtectedRouteAdmin.jsx
  frontend/src/components/admin/TableProduct.jsx
  frontend/src/components/admin/TableProduct2.jsx
  frontend/src/components/ui/calendar.jsx
  frontend/src/components/ui/popover.jsx
  frontend/src/data/user.js
  frontend/src/pages/admin/Dashboard.jsx
  frontend/src/pages/admin/Layout.jsx
  frontend/src/pages/admin/ManageProduct.jsx
  frontend/src/utils/checkUserRole.js
  frontend/src/utils/protectedRouteAdmin.js
Labels: bug, documentation

#31 code hoàn chỉnh v1, mer về đi ạ
  README.md
  backend/controllers/productController.js
  frontend/src/components/admin/FormAddDepot.jsx
  frontend/src/components/admin/TableProduct.jsx
  frontend/src/pages/admin/ManageProduct.jsx
Labels: bug, documentation

#33 FE: add product depot
  backend/.vscode/settings.json
  backend/controllers/productController.js
  backend/controllers/productDepotController.js
  backend/models/index.js
  backend/routes/categoryRoute.js
  backend/routes/productRoute.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin/AdminProductDetail.jsx
  frontend/src/components/admin/FormAddDepot.jsx
  frontend/src/components/admin/TableDepot.jsx
  frontend/src/components/admin/TableProduct.jsx
  frontend/src/components/ui/dialog.jsx
  frontend/src/components/ui/input.jsx
  frontend/src/components/ui/tooltip.jsx
  frontend/src/pages/admin/ManageProduct.jsx
Labels: documentation

#36 FE: fix const Protected Route Admin
  backend/controllers/index.js
  backend/routes/index.js
  frontend/src/components/admin/ProtectedRouteAdmin.jsx
Labels: bug, documentation

#37 feat: product management conf
  backend/controllers/productController.js
  backend/models/product.model.js
  backend/routes/productRoute.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/admin/FormAddProduct.jsx
  frontend/src/components/admin/TableCategory.jsx
  frontend/src/components/admin/TableProduct.jsx
Labels: bug, documentation

#39 feat: conf product mangement
  backend/controllers/productController.js
  backend/controllers/productDepotController.js
  backend/routes/productRoute.js
  frontend/src/components/admin/FormAddDepot.jsx
  frontend/src/components/admin/TableDepot.jsx
  frontend/src/components/admin/TableProduct.jsx
  frontend/src/pages/admin/ManageProduct.jsx
Labels: documentation

#40 Thiendd
  backend/controllers/productController.js
  backend/routes/productRoute.js
  frontend/src/App.jsx
  frontend/src/components/ProductCard.jsx
  frontend/src/pages/main/ProductDetail.jsx
  frontend/src/pages/main/ProductList.jsx
Labels: documentation

#44 fix tab max size height component
  backend/controllers/cartController.js
  backend/controllers/orderController.js
  backend/routes/cartRoute.js
  backend/routes/orderRoute.js
  frontend/src/components/auth/YourOrder.jsx
  frontend/src/pages/auth/UserProfile.jsx
  frontend/src/pages/main/CartPage.jsx
Labels: bug, documentation

#45 Thiendd
  backend/controllers/roleController.js
  backend/controllers/userController.js
  backend/models/user.model.js
  backend/routes/roleRoute.js
  backend/routes/userRoute.js
  db/HolaWearV1.users.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/UserTable.jsx
  frontend/src/pages/admin/ManageUser.jsx
  frontend/src/pages/admin/ManageUserDetail.jsx
Labels: documentation

#46 feat: finish order management page in user
  backend/controllers/authController.js
  backend/controllers/orderController.js
  frontend/src/assets/pleased.png
  frontend/src/components/auth/YourOrder.jsx
Labels: documentation

#60 Chungdt
  backend/controllers/authController.js
  backend/controllers/cartController.js
  backend/controllers/orderController.js
  backend/middlewares/verifySignUp.js
  frontend/src/App.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/OrderTable.jsx
  frontend/src/components/ProductCard.jsx
  frontend/src/components/SideBarAdmin.jsx
  frontend/src/components/admin/ProtectedRouteAdmin.jsx
  frontend/src/components/admin/ProtectedRouteByRole.jsx
  frontend/src/pages/admin/Dashboard.jsx
  frontend/src/pages/auth/RegisterPage.jsx
  frontend/src/pages/main/Checkout.jsx
  frontend/src/pages/main/ProductDetail.jsx
  frontend/src/utils/checkUserRole.js
Labels: documentation

#61 feat: order manage seller
  frontend/src/components/OrderTable.jsx
  frontend/src/components/ui/calendar.jsx
  frontend/src/pages/admin/Dashboard.jsx
Labels: documentation

#62 bug: modify order detail show wrong product image
  backend/controllers/authController.js
  backend/controllers/orderController.js
  backend/controllers/userController.js
  backend/middlewares/sendMail.js
  backend/middlewares/verifyInput.js
  frontend/src/components/auth/YourOrder.jsx
Labels: bug

#65 Fix: GetAllProduct
  backend/controllers/productController.js
  frontend/src/App.jsx
  frontend/src/components/Banner.jsx
  frontend/src/components/BannerSale.jsx
  frontend/src/components/Header.jsx
  frontend/src/pages/main/ProductList.jsx
  package-lock.json
Labels: documentation, help wanted, good first issue

#67 send email after order
  backend/controllers/orderController.js
  backend/package-lock.json
  backend/package.json
  backend/templates/orderEmail.html
Labels: documentation

#69 Buy Now
  frontend/src/pages/main/ProductDetail.jsx
Labels: documentation
